apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingpong
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pingpong
        spec:
          containers:
          - name: pingpong
            image: gihyodocker/alpine:bash
            command: ["/bin/bash"]
            args:
            - "-c"
            - |
              echo [ERR]  `date` ping!
              sleep 10
              echo [INFO] `date` pong!
          restartPolicy: OnFailure
